/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Shooting.glb 
*/

import { useGLTF } from "@react-three/drei";
import TransitionMaterial from "../../MeshTransitionMaterial/MeshTransitionMaterial";

export default function Shooting({ transitionColor }, props) {
  const { nodes, materials } = useGLTF("/Shooting.glb");

  // Material customization
  // Shirt Shoulders
  materials.Shoulder_FRONT_1931.color.set("lime");
  // Shorts
  materials.Short_FRONT_1921.color.set("lime");
  // Sock-Bottom
  materials.Bottom_Socks_FRONT_1951.color.set("lightblue");
  // Collar
  materials.Collar_FRONT_1926.color.set("lime");
  // Main Shirt Area
  materials["Shirt_FRONT_1911.001"].color.set("salmon");
  // Lower Shirt Area
  materials.Lower_Shirt_FRONT_1936.color.set("blue");
  // Socks
  materials.Socks_FRONT_1916.color.set("lime");
  // Upper Socks Part
  materials.Upper_Socks_FRONT_1946.color.set("lightblue");
  // Manniquin Skin
  materials["Model.001"].color.set("#1b1b1b");

  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.23, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 4]}
        scale={0.012}
      >
        <mesh
          geometry={nodes.Shooting_1.geometry}
          material={materials.Waist_FRONT_1941}
        />
        <mesh
          geometry={nodes.Shooting_2.geometry}
          material={materials.Short_FRONT_1921}
          receiveShadow
        />
        <mesh
          geometry={nodes.Shooting_3.geometry}
          material={materials.Bottom_Socks_FRONT_1951}
        />
        <mesh
          geometry={nodes.Shooting_4.geometry}
          material={materials.Collar_FRONT_1926}
        />
        <mesh
          geometry={nodes.Shooting_5.geometry}
          material={materials.Shoulder_FRONT_1931}
        />

        {/* Transitional Material */}
        <mesh
          geometry={nodes.Shooting_6.geometry}
          material={materials["Shirt_FRONT_1911.001"]}
          receiveShadow
        >
          <TransitionMaterial
            transitionColor={transitionColor}
            sheen={1}
            transitionTime={0.4}
          />
        </mesh>
        <mesh
          geometry={nodes.Shooting_7.geometry}
          material={materials.Lower_Shirt_FRONT_1936}
        />
        <mesh
          geometry={nodes.Shooting_8.geometry}
          material={materials.Socks_FRONT_1916}
        />
        <mesh
          geometry={nodes.Shooting_9.geometry}
          material={materials.Upper_Socks_FRONT_1946}
        />
        <mesh
          geometry={nodes.Shooting_10.geometry}
          material={materials["Model.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Shooting.glb");
