/* eslint-disable react/prop-types */
// Ball.jsx
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ballLime.glb 
*/

import { useGLTF } from "@react-three/drei";

export default function Ball({ activeModel, ...props }) {
  // Accept activeModel prop
  const { nodes, materials } = useGLTF("/ballLime.glb");

  // Material: Ball
  materials.FootBall.color.set("gold");

  // Position data
  const ballPositions = {
    Shooting: { position: [-0.9, 0.13, 0.38], scale: 1.2 },
    StandOnBall: { position: [0.2, 0.13, 0.5], scale: 1.25 },
    Tackle: { position: [0.18, 0.13, 1.5], scale: 1.2 },
    LaPulga: { position: [-0.8, 0.13, 0.2], scale: 1.2 },
    Jude: { position: [0, 0.13, 0], scale: 1.2 }, // Default to Jude's position
  };

  const { position, scale } = ballPositions[activeModel] || ballPositions.Jude; // Use Jude's position as default

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.FootBall.geometry}
        material={materials.FootBall}
        position={position} // Dynamic position
        scale={scale} // Dynamic scale
      >
        <mesh geometry={nodes.Seams.geometry} material={materials.Seams} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/ballLime.glb");
