/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cone.glb 
*/

import { useGLTF } from "@react-three/drei";

export default function Cone({ position, ...props }) {
  const { nodes, materials } = useGLTF("/Cone.glb");
  return (
    <group {...props} dispose={null} scale={0.8} position={position}>
      <mesh
        geometry={nodes["Traffic_Cone_Sign_Low-Poly"].geometry}
        material={materials.TrafficConeLP_Material}
        position={[0, 0, -0.003]}
      />
    </group>
  );
}

useGLTF.preload("/Cone.glb");
