/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GOAT.glb 
*/

import { useGLTF } from "@react-three/drei";

export default function Goat(props) {
  const { nodes, materials } = useGLTF("/GOAT.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[-0.8, 0.12, 3]}
      rotation={[0, 4, 0]}
    >
      <group position={[0, 0.382, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={
              materials["tripo_material_15140e0d-177b-4bbd-9d80-547867c64b5f"]
            }
          />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Gold} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/GOAT.glb");
